version: "3.3"

services:

  traefik:
    image: "traefik:v2.5"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  app-root:
    image: "app-root"
    container_name: "app-root"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app-root.rule=PathPrefix(`/`)"
      - "traefik.http.routers.app-root.entrypoints=web"

  app-one:
    image: "app-one"
    container_name: "app-one"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app-one.rule=PathPrefix(`/app-one`)"
      - "traefik.http.routers.app-one.entrypoints=web"

  app-two:
    image: "app-two"
    container_name: "app-two"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app-two.rule=PathPrefix(`/app-two`)"
      - "traefik.http.routers.app-two.entrypoints=web"

  app-three:
    image: "app-three"
    container_name: "app-three"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app-three.rule=PathPrefix(`/app-three`)"
      - "traefik.http.routers.app-three.entrypoints=web"